# Generated by Django 2.2.3 on 2019-07-23 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=100)),
                ('cell_size_hectares', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish_name', models.CharField(max_length=100)),
                ('parish_size_hectares', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parish_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubcountyStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(max_length=25)),
                ('staff_contact', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('district_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_subcounty_staff', to='structures.District')),
                ('user_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounty_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcounty_name', models.CharField(max_length=100)),
                ('subcounty_size_hectares', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounty_creator', to=settings.AUTH_USER_MODEL)),
                ('district_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_district_subcounty', to='structures.District')),
            ],
        ),
        migrations.CreateModel(
            name='ParishStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(max_length=25)),
                ('staff_contact', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parish_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_parish_staff', to='structures.Parish')),
                ('user_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parish_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parish',
            name='subcounty_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_subcounty_parish', to='structures.Subcounty'),
        ),
        migrations.CreateModel(
            name='DistrictStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(max_length=25)),
                ('staff_contact', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('district_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_district_staff', to='structures.District')),
                ('user_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CellStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(max_length=25)),
                ('staff_contact', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('district_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cell_staff', to='structures.Cell')),
                ('user_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='parish_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_parish_cell', to='structures.Parish'),
        ),
    ]
